
const usuarioTipo = {

    EMAIL_SIGN_IN_COMECO:'EMAIL_SIGN_IN_COMECO',
    CADASTRAR_IN_SUCESSO: 'CADASTRAR_IN_SUCESSO',
    CHECARUSUARIOSESSAO: 'CHECARUSUARIOSESSAO',
    SAIR_OUT_USUARIO_COMECO: 'SAIR_OUT_USUARIO_COMECO',
    SAIR_OUT_USUARIO_SUCESSO: 'SAIR_OUT_USUARIO_SUCESSO',
    USUARIO_ERROR: 'USUARIO_ERROR',
    RECUPERAR_PASSWORD_COMECO: 'RECUPERAR_PASSWORD_COMECO',
    RECUPERAR_PASSWORD_SUCESSO: 'RECUPERAR_PASSWORD_SUCESSO',
    RESET_USUARIO_STATE: 'RESET_USUARIO_STATE',
    SIGN_UP_USUARIO_COMECO: 'SIGN_UP_USUARIO_COMECO',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    CADASTRAR_UP_SUCESSO: 'CADASTRAR_UP_SUCESSO',
    CADASTRAR_UP_ERROR: 'CADASTRAR_UP_ERROR',
    RESET_PASSWORD_SUCESSO: 'RESET_PASSWORD_SUCESSO',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
    RESET_AUTH_FORMULARIO: 'RESET_AUTH_FORMULARIO',
    GOOGLE_CADASTRAR_COMECO: 'GOOGLE_CADASTRAR_COMECO'
};

export default usuarioTipo;